### ISSUE TITLE
If you'd love to see a `docker-compose` example in our docs, click ❤️

### ISSUE THREAD

**Issue by mick-prysm** [prysmaticlabs/documentation#663]
Our [current docker docs](https://docs.prylabs.network/docs/install/install-with-docker) don't include `docker-compose` instructions, [as recently suggested by Gs over on Discord](https://discord.com/channels/476244492043812875/667763844365680650/1037860803581317180) (thank you again!). Their suggestion included an example:

```
version: "3.6"
services:
  beacon-node-mainnet:
    command: --datadir=/data --rpc-host=0.0.0.0 --monitoring-host=0.0.0.0 --execution-endpoint=<YOUR_ETH_EXECUTION_NODE_ENDPOINT> --jwt-secret <YOUR_JWT_SECRET> --p2p-max-peers 45 --block-batch-limit 64
    container_name: beacon-node-mainnet
    entrypoint:
      - /app/cmd/beacon-chain/beacon-chain
    image: gcr.io/prysmaticlabs/prysm/beacon-chain:stable
    network_mode: bridge
    ports:
      - 12000:12000/udp
      - 13000:13000/tcp
      - 4000:4000/tcp
      - 8080:8080/tcp
    restart: unless-stopped
    stdin_open: true
    tty: true
    user: root
    volumes:
      - datadir:/data
    stop_grace_period: 1m30s
```

[stefa2k.eth provided some additional examples here](https://github.com/stereum-dev/ethereum2-docker-compose/blob/master/compose-examples/prysm-only/docker-compose.yaml) later in the [Discord discussion](https://discord.com/channels/476244492043812875/667763844365680650/1038026780369485925).

If you'd _love_ to see `docker-compose` examples in our docs, clicking ❤️  will help us understand how much of a need there is for this content. Thank you  🙏
